version: '3.4'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  clients.authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  logistic.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  transport.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
