// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Transport.Persistence;

namespace Transport.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220811134046_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Transport.Domain.Models.Transportt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("License")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusMode")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for transport 1",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for transport 2",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for transport 3",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for transport 4",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for transport 5",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description for transport 6",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description for transport 7",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description for transport 8",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description for transport 9",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description for transport 10",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
