// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transport.Persistence;

#nullable disable

namespace Transport.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925022302_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Transport.Domain.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<byte>("Test")
                        .HasMaxLength(5)
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Transport.Domain.Models.Transportt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("License")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StatusMode")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Transports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Description for transport 1",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Description for transport 2",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "Description for transport 3",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "Description for transport 4",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Description = "Description for transport 5",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Description = "Description for transport 6",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Description = "Description for transport 7",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Description = "Description for transport 8",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Description = "Description for transport 9",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Description = "Description for transport 10",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
